name: Scala CI

on:
  push:
    branches: [main, develope, feature-luis]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: 'sbt'
      - name: Run tests and generate coverage
        run: |
          sbt clean coverage test
          sbt coverageReport
      - name: Exclude folders from coverage report
        run: |
           echo "Before sed:"
           cat target/scala-2.13/scoverage-report/scoverage.xml
           sed -i '/aview/d' target/scala-2.13/scoverage-report/scoverage.xml
           sed -i '/util/d' target/scala-2.13/scoverage-report/scoverage.xml
           sed -i '/Kniffel.scala/d' target/scala-2.13/scoverage-report/scoverage.xml
           echo "After sed:"
           cat target/scala-2.13/scoverage-report/scoverage.xml
      - name: Upload coverage to Coveralls
        run: sbt coveralls
